apiVersion: v1
kind: ConfigMap
metadata:
  name: autfw-ui-config
data:
  # property-like keys; each key maps to a simple value
  ADMIN_ACCOUNTS: "benoit@vmware.com"
  ADMIN_ORGCODE: "abcde"
  COOKIE_SECRET: "kjdjmkjfqmljfmlqjdfmljqlmkfjldmjmqjflmjfljqslmjlfj=="
  DB_CONNECTION_STRING: "mongodb://sample-mongodb-account-beta:dkslqjdlkqjsdlkqskldjqslkjd==@sample-mongodb-account-beta.mongo.cosmos.azure.com:10255/?ssl=true&replicaSet=globaldb&retrywrites=false&maxIdleTimeMS=120000&appName=@sample-mongodb-account-beta@"
  DB_NAME: "bigdevdatabase"
  MONGODB_ADDON_URI: mongodb://sample-mongodb-account-beta:mMmWOSsEMniWDo9Uha1hrUMWae4g3Zzk3fzO2DBoMRHbtfeBWxsxCrcN4xRBJcHIwhfHNhN4Oj8oACDbNpNgdQ==@sample-mongodb-account-beta.mongo.cosmos.azure.com:10255/?ssl=true&replicaSet=globaldb&retrywrites=false&maxIdleTimeMS=120000&appName=@sample-mongodb-account-beta@
---
apiVersion: v1
kind: Secret
metadata:
  name: secured-autfw-ui-config
stringData:
  # property-like keys; each key maps to a simple value
  ADMIN_ACCOUNTS: "benoit@vmware.com"
  ADMIN_ORGCODE: "abcde"
  COOKIE_SECRET: "kjdjmkjfqmljfmlqjdfmljqlmkfjldmjmqjflmjfljqslmjlfj=="
  DB_CONNECTION_STRING: "mongodb://sample-mongodb-account-beta:dkslqjdlkqjsdlkqskldjqslkjd==@sample-mongodb-account-beta.mongo.cosmos.azure.com:10255/?ssl=true&replicaSet=globaldb&retrywrites=false&maxIdleTimeMS=120000&appName=@sample-mongodb-account-beta@"
  DB_NAME: "bigdevdatabase3"
---
apiVersion: services.apps.tanzu.vmware.com/v1alpha1
kind: ResourceClaim
metadata:
  name: autfw-ui-config-rc
  namespace: dev-tap
spec:
  ref:
    apiVersion: v1
    kind: Secret
    name: secured-autfw-ui-config
    namespace: dev-tap
---
apiVersion: servicebinding.io/v1beta1
kind: ServiceBinding
metadata:
  labels:
    app.kubernetes.io/component: run
    app.kubernetes.io/part-of: simple-mongodb-app
  name: simple-mongodb-app-game-demo-config
  namespace: dev-tap
spec:
  name: autfw-ui-config
  service:
    apiVersion: services.apps.tanzu.vmware.com/v1alpha1
    kind: ResourceClaim
    name: autfw-ui-config-rc
  workload:
    apiVersion: apps/v1
    kind: Deployment
    name: simple-mongodb-app
  env:
    - name: DB_NAME
      key: DB_NAME
    - name: ADMIN_ACCOUNTS
      key: ADMIN_ACCOUNTS
    - name: ADMIN_ORGCODE
      key: ADMIN_ORGCODE
    - name: COOKIE_SECRET
      key: COOKIE_SECRET
