---
apiVersion: services.apps.tanzu.vmware.com/v1alpha1
kind: ClusterInstanceClass
metadata:
  name: azure-mongodb
spec:
  description:
    short: Azure CosmoDB instances with a MongoDB engine
  pool:
    kind: Secret
    labelSelector:
      matchLabels:
        services.apps.tanzu.vmware.com/class: azure-mongodb
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: azure-mongodb-servicebinding-controller-secret-reader
  labels:
    servicebinding.io/controller: "true"
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
---
apiVersion: services.apps.tanzu.vmware.com/v1alpha1
kind: ResourceClaimPolicy
metadata:
  name: developer-in-dev-tap-can-claim-azure-mongodb
  namespace: mongodb-instances-fr
spec:
  subject:
    kind: Secret
    group: ""
    selector:
      matchLabels:
        services.apps.tanzu.vmware.com/class: azure-mongodb
  consumingNamespaces:
  - '*'
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mongo-sa-reader
  namespace: mongodb-instances-fr
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: azure-mongodb-reading
  namespace: mongodb-instances-fr
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
  resourceNames:
  - db-secret
- apiGroups:
  - documentdb.azure.com
  resources:
  - mongodbdatabases
  verbs:
  - get
  - list
  - watch
  resourceNames:
  - sample-db-mongodb-beta
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: azure-mongodb-reader-to-read
  namespace: mongodb-instances-fr
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: azure-mongodb-reading
subjects:
- kind: ServiceAccount
  name: mongo-sa-reader
  namespace: mongodb-instances-fr
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretTemplate
metadata:
  name: mongodb-credentials-azure-exposed
  namespace: mongodb-instances-fr
spec:
  serviceAccountName: mongo-sa-reader
  inputResources:  
  - name: db
    ref:
      apiVersion: documentdb.azure.com/v1beta20210515
      kind: MongodbDatabase
      name: sample-db-mongodb-beta
  - name: creds
    ref:
      apiVersion: v1
      kind: Secret
      name: db-secret
  template:
    metadata:
      labels:        
        services.apps.tanzu.vmware.com/class: azure-mongodb    
    type: Opaque
    stringData:
      type: mongodb
      port: "10255"
      host: $(.db.status.name).mongo.cosmos.azure.com      
      username: sample-mongodb-account-beta
    data:
      password: $(.creds.data.primarymasterkey)
---
apiVersion: services.apps.tanzu.vmware.com/v1alpha1
kind: ResourceClaim
metadata:
  name: mongodb-database-local
  namespace: dev-tap
spec:
  ref:
    apiVersion: v1
    kind: Secret
    name: mongodb-credentials-local
    namespace: dev-tap
---
apiVersion: services.apps.tanzu.vmware.com/v1alpha1
kind: ResourceClaim
metadata:
  name: mongodb-database-azure-exposed
  namespace: dev-tap
spec:
  ref:
    apiVersion: v1
    kind: Secret
    name: mongodb-credentials-azure-exposed
    namespace: mongodb-instances-fr
---
apiVersion: services.apps.tanzu.vmware.com/v1alpha1
kind: ResourceClaim
metadata:
  name: mongodb-database-remote
  namespace: dev-tap
spec:
  ref:
    apiVersion: v1
    kind: Secret
    name: mongodb-credentials-manually-managed
    namespace: mongodb-instances-fr

