apiVersion: services.apps.tanzu.vmware.com/v1alpha1
kind: ResourceClaim
metadata:
  name: autfw-ui-config-rc
  namespace: dev-tap
spec:
  ref:
    apiVersion: v1
    kind: Secret
    name: secured-autfw-ui-config
    namespace: dev-tap
---
apiVersion: servicebinding.io/v1beta1
kind: ServiceBinding
metadata:
  labels:
    app.kubernetes.io/component: run
    app.kubernetes.io/part-of: simple-mongodb-app
  name: simple-mongodb-app-game-demo-config
  namespace: dev-tap
spec:
  name: autfw-ui-config
  service:
    apiVersion: services.apps.tanzu.vmware.com/v1alpha1
    kind: ResourceClaim
    name: autfw-ui-config-rc
  workload:
    apiVersion: apps/v1
    kind: Deployment
    name: simple-mongodb-app
  env:
    - name: DB_NAME
      key: DB_NAME
    - name: ADMIN_ACCOUNTS
      key: ADMIN_ACCOUNTS
    - name: ADMIN_ORGCODE
      key: ADMIN_ORGCODE
    - name: COOKIE_SECRET
      key: COOKIE_SECRET
