apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: simple-mongodb-app
  annotations:
    serviceclaims.supplychain.apps.x-tanzu.vmware.com/extensions: '{"kind":"ServiceClaimsExtension","apiVersion":"supplychain.apps.x-tanzu.vmware.com/v1alpha1","spec":{"serviceClaims":{"my-mongodb-database":{"namespace":"mongodb-instances-fr"}}}}'
  labels:
    apps.tanzu.vmware.com/workload-type: server
    app.kubernetes.io/part-of: simple-mongodb-app
spec:
  source:
    git:
      url: https://github.com/bmoussaud/simple-mongodb-app
      ref:
        branch: main
  env:
    - name: env
      value: development    
  serviceClaims:
    - name: my-mongodb-database
      ref:
        apiVersion: v1
        kind: Secret
        name: mongodb-credentials-azure-exposed
    - name: app-config
      ref:
        apiVersion: v1
        kind: Secret
        name: fwui-app
  params:
    - name: gitops_server_address
      value: https://github.com/
    - name: gitops_repository_owner
      value: bmoussaud
    - name: gitops_repository_name
      value: micropets-app-gitops
    - name: port
      value: 8888
    - name: annotations
      value:
        autoscaling.knative.dev/minScale: "1"
