apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: simple-mongodb-app
  labels:
    apps.tanzu.vmware.com/workload-type: server
    app.kubernetes.io/part-of: simple-mongodb-app
spec:
  source:
    git:
      url: https://github.com/bmoussaud/simple-mongodb-app
      ref:
        branch: main
  env:
    - name: env
      value: development
    - name: MONGODB_ADDON_URI
      valueFrom:
        configMapKeyRef:
          name: autfw-ui-config
          key: MONGODB_ADDON_URI
    - name: ADMIN_ACCOUNTS
      valueFrom:
        configMapKeyRef:
          name: autfw-ui-config
          key: ADMIN_ACCOUNTS
    - name: ADMIN_ORGCODE
      valueFrom:
        configMapKeyRef:
          name: autfw-ui-config
          key: ADMIN_ORGCODE
    - name: COOKIE_SECRET
      valueFrom:
        configMapKeyRef:
          name: autfw-ui-config
          key: COOKIE_SECRET
    - name: DB_CONNECTION_STRING
      valueFrom:
        configMapKeyRef:
          name: autfw-ui-config
          key: DB_CONNECTION_STRING
    - name: DB_NAME
      valueFrom:
        configMapKeyRef:
          name: autfw-ui-config
          key: DB_NAME
  serviceClaims:
    - name: mongodb-database
      ref:
        apiVersion: services.apps.tanzu.vmware.com/v1alpha1
        kind: ResourceClaim
        name: mongodb-database-remote
  params:
    - name: annotations
      value:
        autoscaling.knative.dev/minScale: "1"
