apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: simple-mongodb-app
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: simple-mongodb-app  
spec:
  source:
    git:
      url: https://github.com/bmoussaud/simple-mongodb-app
      ref:
        branch: main
  env:
    - name: env
      value: development
    - name: MONGODB_ADDON_URI_X
      value: mongodb://sample-mongodb-account-beta:mMmWOSsEMniWDo9Uha1hrUMWae4g3Zzk3fzO2DBoMRHbtfeBWxsxCrcN4xRBJcHIwhfHNhN4Oj8oACDbNpNgdQ==@sample-mongodb-account-beta.mongo.cosmos.azure.com:10255/?ssl=true&replicaSet=globaldb&retrywrites=false&maxIdleTimeMS=120000&appName=@sample-mongodb-account-beta@      
  serviceClaims:
    - name: mongodb-database
      ref:
        apiVersion: services.apps.tanzu.vmware.com/v1alpha1
        kind: ResourceClaim
        name: mongodb-database-remote
    

 